service: soluchain-backend
frameworkVersion: "3"
plugins:
  - serverless-offline
  - serverless-appsync-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  environment:
    MESSAGE:
      prod: "PRODUCTION environment"
      dev: "DEVELOPMENT environment"
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  environment:
    MESSAGE: ${self:custom.environment.MESSAGE.${self:custom.stage}}
  httpApi:
    cors: true

functions:
  graphql:
    handler: src/graphql/server.graphqlHandler
    events:
      - httpApi:
          path: /graphql
          method: POST
      - httpApi:
          path: /graphql
          method: GET

resources:
  Resources:
    SoluchainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Soluchain
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gsi1pk
            AttributeType: S
          - AttributeName: gsi1sk
            AttributeType: S
          - AttributeName: gsi2pk
            AttributeType: S
          - AttributeName: gsi2sk
            AttributeType: S
          - AttributeName: gsi3pk
            AttributeType: S
          - AttributeName: gsi3sk
            AttributeType: S
          - AttributeName: gsi4pk
            AttributeType: S
          - AttributeName: gsi4sk
            AttributeType: S
          - AttributeName: gsi5pk
            AttributeType: S
          - AttributeName: gsi5sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gsi1
            KeySchema:
              - AttributeName: gsi1pk
                KeyType: HASH
              - AttributeName: gsi1sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: gsi2
            KeySchema:
              - AttributeName: gsi2pk
                KeyType: HASH
              - AttributeName: gsi2sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: gsi3
            KeySchema:
              - AttributeName: gsi3pk
                KeyType: HASH
              - AttributeName: gsi3sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: gsi4
            KeySchema:
              - AttributeName: gsi4pk
                KeyType: HASH
              - AttributeName: gsi4sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: gsi5
            KeySchema:
              - AttributeName: gsi5pk
                KeyType: HASH
              - AttributeName: gsi5sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
