export const limits = {
  // Campaign
  MIN_CAMPAIGN_TITLE_LENGTH: 3,
  MAX_CAMPAIGN_TITLE_LENGTH: 100,
  MIN_CAMPAIGN_DESCRIPTION_LENGTH: 100,
  MAX_CAMPAIGN_DESCRIPTION_LENGTH: 2000,
  ALLOWED_TAGS: [
    "a",
    "b",
    "i",
    "u",
    "br",
    "p",
    "ul",
    "ol",
    "li",
    "strong",
    "em",
    "blockquote",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
  ],
  MAX_PROFILES_PER_PAGE: 20,
  MAX_CAMPAIGNS_PER_PAGE: 20,
};
